#!/usr/bin/env node
/**
 * Convert usda-output.json to lib/data/seedFoods.ts
 *
 * Usage:
 *   node scripts/json-to-seed.js
 *
 * Reads: scripts/usda-output.json
 * Writes: lib/data/seedFoods.ts
 */

const fs = require('fs');
const path = require('path');

function toSeedId(id) {
  return 'seed-' + id.replace(/_/g, '-').replace(/([a-z])([A-Z])/g, '$1-$2').toLowerCase().slice(0, 20);
}

function pad4(n) {
  return String(n).padStart(4, '0');
}

function main() {
  const inputPath = path.join(__dirname, 'usda-output.json');
  const outputPath = path.join(__dirname, '..', 'lib', 'data', 'seedFoods.ts');

  if (!fs.existsSync(inputPath)) {
    console.error('Missing usda-output.json. Run: node scripts/fetch-usda-seeds.js first');
    process.exit(1);
  }

  const foods = JSON.parse(fs.readFileSync(inputPath, 'utf8'));

  // Load comprehensive Mongolian names for all foods (covers 300+ foods)
  const mnNamesPath = path.join(__dirname, 'mn-food-names.json');
  const FOOD_ID_TO_MN = fs.existsSync(mnNamesPath)
    ? JSON.parse(fs.readFileSync(mnNamesPath, 'utf8'))
    : {};

  foods.forEach((f) => {
    f.aliases = f.aliases || [];
    const mnTerms = FOOD_ID_TO_MN[f.id];
    if (mnTerms && Array.isArray(mnTerms)) {
      // Use first Mongolian term as name_mn (primary display name)
      f.name_mn = mnTerms[0].trim();
      for (const mn of mnTerms) {
        const term = mn.trim().toLowerCase();
        if (term && !f.aliases.includes(term)) f.aliases.push(term);
      }
    }
  });

  // Write back usda-output.json with Mongolian name_mn
  fs.writeFileSync(inputPath, JSON.stringify(foods, null, 2), 'utf8');
  console.log(`Updated ${inputPath} with Mongolian name_mn`);

  const seedIdsLines = [];
  const seedFoodsLines = [];

  foods.forEach((f, i) => {
    const seedId = `${toSeedId(f.id)}-${pad4(i + 1)}`;
    seedIdsLines.push(`  ${f.id}: '${seedId}',`);
    seedFoodsLines.push(`  {
    id: '${f.id}',
    name_mn: '${f.name_mn.replace(/'/g, "\\'")}',
    name_en: '${(f.name_en || f.name_mn).replace(/'/g, "\\'").slice(0, 80)}',
    calories_per_100g: ${f.calories_per_100g},
    protein_g_per_100g: ${f.protein_g_per_100g},
    carbs_g_per_100g: ${f.carbs_g_per_100g},
    fat_g_per_100g: ${f.fat_g_per_100g},
    aliases: [${(f.aliases || [f.name_mn.toLowerCase()]).map((a) => `'${String(a).replace(/'/g, "\\'")}'`).join(', ')}],
    portions: [${(f.portions || [{ label_mn: '100г', grams: 100, is_default: 1 }])
      .map((p) => `{ label_mn: '${p.label_mn}', grams: ${p.grams}, is_default: ${p.is_default ?? 0} }`)
      .join(', ')}],
  },`);
  });

  const content = `/**
 * Seed foods - 300+ common Western foods with accurate macros from USDA.
 * Generated by: node scripts/fetch-usda-seeds.js && node scripts/json-to-seed.js
 */

export const SEED_IDS: Record<string, string> = {
${seedIdsLines.join('\n')}
};

export interface SeedFood {
  id: string;
  name_mn: string;
  name_en: string;
  calories_per_100g: number;
  protein_g_per_100g: number;
  carbs_g_per_100g: number;
  fat_g_per_100g: number;
  aliases: string[];
  portions: Array<{ label_mn: string; grams: number; is_default: number }>;
}

export const SEED_FOODS: SeedFood[] = [
${seedFoodsLines.join('\n')}
];
`;

  fs.mkdirSync(path.dirname(outputPath), { recursive: true });
  fs.writeFileSync(outputPath, content, 'utf8');
  console.log(`Wrote ${outputPath} (${foods.length} foods)`);
}

main();
